### ISSUE TITLE
invalid_requests

### ISSUE THREAD

**Issue by jbdo99** [hammerandchisel/discord-oauth2-example#1]
Hi, I test the script for oauth2 and I have a problem : 

I open my localhost:5000
I accept on the page with authorizations 
I get A missmatching redirect URl with an url like that : `https://discordapp.com/oauth2/error?error=invalid_request&error_description=Mismatching+redirect+URI.
`

When I configure my bot and i add URi with the /callback, the page respond : `mydomaine:5000/callback?error=invalid_request&error_description=Missing+response_type+parameter.` and show invalid_request

Thank's for reading and I hope you can help me !

Jbdo99

**Comment by JustMaffie** [comment]
On the applications page, add a redirect: https://gyazo.com/77f7a55b840017a86dfa1af7b9c4f560
Make sure it is the exact url of the callback.
