### ISSUE TITLE
redirect_uri doesn't accept custom handlers?

### ISSUE THREAD

**Issue by Nexuist** [hammerandchisel/discord-oauth2-example#3]
Hi there. I'm trying to make an iOS app that allows Discord login via OAuth. I'm currently showing the following page in my app: `https://discordapp.com/api/oauth2/authorize?client_id=\(clientID)&scope=rpc.api&redirect_uri=myapp://`

Unfortunately I only get an unknown_error message telling me to close the window/tab. I tried to register myapp:// as a redirect URI in the dev console but it will not let me (says errors encountered, status code 400).

The authorize page works perfectly fine as long as I don't specify a redirect_uri, but of course that also makes it pointless. Is this not allowed? Or am I doing it wrong?

Thanks,
Andi

**Comment by night** [comment]
We do not accept custom handlers at this time, sorry. You may be able to setup a server to handle deep linking into your app upon redirection. Feature requests for the API can be submitted on our docs repo: https://github.com/hammerandchisel/discord-api-docs
